[package]
name = "graphrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "2.2.0"
chrono = "0.4.19"
gl = "0.14.0"
glfw = "0.43.0"
glium = "0.31.0"
imgui = "0.8.2"
imgui-glium-renderer = "0.8.2"
imgui-winit-support = "0.8.2"
itertools = "0.10.3"
speedy = "0.8.1"
winit = "0.26.1"
