[package]
name = "graphrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
gl = "0.14.0"
glfw = "0.43.0"
glium = "0.30.2"
glutin = "0.27.0"
imgui = "0.8.2"
imgui-glium-renderer = "0.8.2"
imgui-winit-support = {version = "0.8.2", features = ["winit-25"]}
itertools = "0.10.3"
nalgebra = "0.30.1"
speedy = "0.8.1"
winit = "0.25.0"

