[package]
name = "test_format"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph_format = { path = "../graph_format" }
serde = { version = "1.0", features = ["derive"] }
speedy = "0.8"